### ISSUE TITLE
fs 类型，保存后，重启，会丢失

### ISSUE THREAD

**Issue by caihaibin1991** [hexindai/egg-cache#10]

**Comment by caihaibin1991** [comment]
这边项目都是独立部署型，所以不用redis什么的.filecache相对实用些。麻烦有没有空看下？

**Comment by seekcx** [comment]
我看看

**Comment by seekcx** [comment]
我尝试了一下，fs 驱动重启后第一次请求会丢失，后面能读到值，这是驱动问题。

更换了 fs-hash 驱动没有出现这个问题，下面是我的代码。

```js
// app/controller/home.js
'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    const { app, ctx } = this;
    // await app.cache.set('name', 'abel', 10000);

    ctx.body = await app.cache.get('name');
  }
}

module.exports = HomeController;

// config/config.default.js
'use strict';

const fsHashStore = require('cache-manager-fs-hash');

const config = {
  keys: '_1592883898774_4939',
  cache: {
    default: 'fsHash',
    stores: {
      fsHash: {
        driver: fsHashStore,
        path: 'cache',
      },
    },
  },
};

module.exports = config;
```

**Comment by caihaibin1991** [comment]
也边还会。。。我想想。不过这边用的是midway egg的ts版本

**Comment by caihaibin1991** [comment]
上面这种不正常
// import {cacheManagerFs} from 'cache-manager-fs';
下面这种正常
import * as cacheManagerFs from "cache-manager-fs";

**Comment by seekcx** [comment]
这两种方式是有差异的

**Comment by seekcx** [comment]
另外我感觉 fs 的工作方式有点诡异，同样的 key 会生成不同的缓存文件，偶尔会交替的读到两个缓存值，fs-hash 就很清晰。

这个问题先关闭了，如果还有问题可以再次打开。

**Comment by caihaibin1991** [comment]
好的。谢谢。 我建议补充下类型检测，如果确实defaultStore用了别的，对应驱动为空，直接报错会比较合适，这样可以避免走了内存驱动还不知道。。。

**Comment by seekcx** [comment]
现在如果访问了不存在的驱动也会抛出错误的 https://github.com/hexindai/egg-cache/blob/master/lib/cache.js#L16-L18 
如果是 defalultStore 指定的驱动不存在的话确实应该启动的时候就抛出，稍后我调整一下。

**Comment by caihaibin1991** [comment]
对了，还有个问题。不清楚是不是midway这边才会。我这边启动立马访问cache，第一次会返回空。第二次就可以读取到值了。
不知道为什么，为了避免程序出问题，我这边在初始化时，主动访问cache......

**Comment by seekcx** [comment]
用的什么驱动？

**Comment by caihaibin1991** [comment]
fs

**Comment by caihaibin1991** [comment]
可能就是你说的诡异问题。。。。

**Comment by seekcx** [comment]
fs 有这个问题，我测试的是有也是这样。用 fs-hash 没这个问题。

**Comment by caihaibin1991** [comment]
好的。谢谢
