### ISSUE TITLE
expire单位好像不是秒，是毫秒？

### ISSUE THREAD

**Issue by AM-young-fun** [hexindai/egg-cache#13]

**Comment by Runrioter** [comment]
@AntiMoron 此仓库基于 [node-cache-manager](https://github.com/node-cache-manager/node-cache-manager)。node-cache-manager老版本是单位是秒，新版才是毫秒。

此仓库用的是上述库的老版本^2.9.0 因此单位是秒。

See more [https://github.com/node-cache-manager/node-cache-manager/pull/203]
