### ISSUE TITLE
切换到ioredis保存

### ISSUE THREAD

**Issue by relzhong** [hexindai/egg-cache#6]
![image](https://user-images.githubusercontent.com/12643564/43121099-28748da8-8f4f-11e8-93bf-1b746aeb0b2c.png)

**Comment by seekcx** [comment]
切换到 redis 的驱动跑的测试吗？

**Comment by relzhong** [comment]
是的,ioredis 的set返回的是OK

**Comment by seekcx** [comment]
cache manager 没有统一不同驱动的返回值，不同的驱动可能需要不同的配置才行，参考这个 pr #3
